FROM golang:1.25-alpine

WORKDIR /app

RUN apk add --no-cache git curl

COPY go.mod go.sum ./
RUN go mod download

RUN go install github.com/air-verse/air@latest

EXPOSE 8888

CMD ["air", "-c", ".air.toml"]
